### ISSUE TITLE
Can't keep conditional counter

### ISSUE THREAD

**Issue by jmnsf** [magnusvk/counter_culture#123]
In an e-commerce store, there is an Article module that has many physical Items. It is useful to keep an `available_items_count` in the Article model that shows available stock for that article.

The current possible solution is having a conditional column name:

```ruby
counter_culture :article, column_name: -> (model) do
  model.available? 'available_items_count' : nil
end
```

But the counter doesn't get updated when the item becomes unavailable, because the column is now nil.

**Comment by magnusvk** [comment]
@jmnsf There's [a test for this case specifically](https://github.com/magnusvk/counter_culture/blob/master/spec/counter_culture_spec.rb#L439). So I doubt that's what is going on. Are you sure that callbacks are fired when the item changes to unavailable? If not, counter_culture has no way of knowing what happened.

If this turns out to be an issue with counter_culture after all, please open a pull request with a failing test added. Otherwise I don't have enough information to go on in searching for a fix.

Thanks for the report.
