### ISSUE TITLE
has_many through counters

### ISSUE THREAD

**Issue by Svashta** [magnusvk/counter_culture#129]
I have this kind of relations:

**NetworkAddress** 
`has_one :asset, inverse_of: :network_address, dependent: :nullify`
`has_one :building, through: :asset`

**Asset**
`belongs_to :network_address, inverse_of: :asset`
`belongs_to :building, inverse_of: :assets`

**Building**
`has_many :assets, through: :rooms`
`has_many :network_addresses, through: :assets`

**Room**
`belongs_to :building, inverse_of: :rooms`
`has_many  :assets, inverse_of: :room, dependent: :nullify`
`has_many  :network_addresses, through: :assets`

Is there any way I could get **network_address_count** on Building?

**Comment by magnusvk** [comment]
This is all documented [in the README](https://github.com/magnusvk/counter_culture/blob/master/README.md#multi-level-counter-cache).

In your case adding `counter_culture [:asset, :building]` on `NetworkAddress` should do the trick.

**Comment by Svashta** [comment]
Sorry Magnus, but I read it more than 10 times, and I have also tried what you gave for example and it didn't do the trick. So I opened this ticket. It simply doesn't do a correct query

**Comment by magnusvk** [comment]
I can't help with this without a lot more information, unfortunately. And I don't really have the time to help debug this even if I had the complete code. If this is due to a bug in counter_culture the best thing you can do is to fork this repository and add a failing test. Then you can pull-request that which will allow me to look into it.

Thanks.
