### ISSUE TITLE
counter_culture_fix_counts update with wrong results

### ISSUE THREAD

**Issue by pChaAnthony** [magnusvk/counter_culture#156]
Maybe I am doing something wrong, I have a pc_blog table, with 3 column each link associated to category/subcategory/subsubcategory.

```
class PcBlog < ActiveRecord::Base
  belongs_to  :subsubcategory1, class_name: "PcSubsubcategory"
    counter_culture [:subsubcategory1, :pc_subcategory, :pc_category], :column_name => "pc_blog_count"
    counter_culture [:subsubcategory1, :pc_subcategory], :column_name => "pc_blog_count"
    counter_culture [:subsubcategory1], :column_name => "pc_blog_count"
  belongs_to  :subsubcategory2, class_name: "PcSubsubcategory"
    counter_culture [:subsubcategory2, :pc_subcategory, :pc_category], :column_name => "pc_blog_count"
    counter_culture [:subsubcategory2, :pc_subcategory], :column_name => "pc_blog_count"
    counter_culture [:subsubcategory2], :column_name => "pc_blog_count"
  belongs_to  :subsubcategory3, class_name: "PcSubsubcategory"
    counter_culture [:subsubcategory3, :pc_subcategory, :pc_category], :column_name => "pc_blog_count"
    counter_culture [:subsubcategory3, :pc_subcategory], :column_name => "pc_blog_count"
    counter_culture [:subsubcategory3], :column_name => "pc_blog_count"
```

the counter_culture works beautifully when subsubcategory1/2/3 column changing with the pc_blog_count in each association updated correctly, however, when I run PcBlog.counter_culture_fix_counts at rails c, it generated different results everytime, as: => [{:entity=>"PcCategory", :id=>1, :what=>"pc_blog_count", :wrong=>1, :right=>2}, {:entity=>"PcCategory", :id=>2, :what=>"pc_blog_count", :wrong=>0, :right=>1}, {:entity=>"PcCategory", :id=>3, :what=>"pc_blog_count", :wrong=>3, :right=>6}, {:entity=>"PcCategory", :id=>7, :what=>"pc_blog_count", :wrong=>1, :right=>0}, {:entity=>"PcSubcategory", :id=>3, :what=>"pc_blog_count"....  
as I am still in development mode, I try 3 times, all with different results, and, the result is not the correct ones.

again, maybe I am doing something wrong...

**Comment by magnusvk** [comment]
Hm; I think the issue here is that you have three different counter caches all modifying the same column: `subsubcategory1`, `subsubcategory2` and `subsubcategory3` all modify the `pc_blog_count` column. When you run fix counts, it'll go look at, say, `PcSubsubcategory` and try and count all the matching `PcBlog`. But that'll fail because it would have to take into account the three different associations; rather, it takes them one at a time.

The way this is "intended" to be used would be to have three separate counter columns for each of these relations. However, if that's not your use case I'd suggest just whipping up a couple of lines of code yourself that correctly fix these counts. I'd imagine that's a lot easier than trying to do this within counter_culture. You can still use the logic that updates caches and just never call `fix_counts` and that should work.

Hope this helps.

**Comment by pChaAnthony** [comment]
Thanks, I thought I was doing something wrong, in this case, I will write a console code to update it, thanks.
