### ISSUE TITLE
Can ignore if related model does not exists.

### ISSUE THREAD

**Issue by kntmrkm** [magnusvk/counter_culture#169]
This is my code.

```
class Account < ApplicationRecord
  belongs_to :category
  counter_culture :category, column_name: ->(o) { o.active? ? 'accounts_count' : nil }
end

class Category < ApplicationRecord
  has_many :accounts
end
```

If one `Account` record does not have `Category`. Then Account's update action will abort.

Below code can update attributes even if `Account`'s `category_id` is nil.

`counter_culture :category, column_name: ->(o) { (o.category_id.present? && o.active?) ? 'accounts_count' : nil }`

Are there a any option to ignore existence of relation?

**Comment by magnusvk** [comment]
It's hard to tell without access to more of the code, but my guess would be that the issue is in your `active?` method. Does it somehow rely on the category id being present? counter_culture itself should be fine with that value being nil; in fact, as far as the counter cache is concerned you shouldn't even need the `column_name` proc at all.

In any case, I can't see a bug in counter_culture with this. If I'm missing something feel free to post more info, in particular a failing test case would be helpful.
