### ISSUE TITLE
Using the "id" attribute in conditional counters can cause counter errors

### ISSUE THREAD

**Issue by WKD** [magnusvk/counter_culture#170]
If you try to use the "id" attribute of your model inside the column_name Proc of a conditional counter cache, you will most likely get counter errors at some point.

Example:

`counter_culture :node, column_name: Proc.new { |ob| obj.id == obj.parent_id && obj.red? ? "root_nodes_count" : nil }`

This will not adjust the counter when the object "turns red" because the first test will ALWAYS be false if parent_id is not nil.

This is because `CounterCulture::Counter#previous_model`  uses `dup` to make a copy of the previous state of the object to compare it with the new state. This call discards the object's id so when counter_culture evaluates the conditions, it will see "false" before and after the update to the object, thus failing to adjust the counter accordingly.

**Comment by magnusvk** [comment]
Yeah, it makes sense that this would happen. I really don't understand your code though; if you're checking whether a node is root, shouldn't you just see if `parent_id` is `nil`? Aka I'm having a hard time seeing a real use case for this.

That being said, the fix is probably simple. Can you open a pull request with a failing test for this? Then the fix is likely just to set the `id` on the duped object.

**Comment by magnusvk** [comment]
Closing for lack of response; feel free to reopen as a PR with a failing test case.
