### ISSUE TITLE
ArgumentError: The method .group() must contain arguments.

### ISSUE THREAD

**Issue by danielbonnell** [magnusvk/counter_culture#181]
I'm running `counter_culture` v1.6.2 (upgrading to 1.7 isn't an option for me currently). I've got a `Contact`, `ContactGroup` and a `Group` model, like so:

    class Contact < ApplicationRecord
        has_many :contact_groups
        has_many :groups, through: :contact_groups

        counter_culture [:contact_groups, :group], touch: true
        counter_culture [:contact_groups, :group],
            column_name: :confirmed_count,
            column_names: { ["contacts.confirmed_at IS NOT NULL"] => 'confirmed_count' },
            touch: true
    end

    class ContactGroup < ApplicationRecord
        belongs_to :contact
        belongs_to :group
        validates_uniqueness_of :contact_id, scope: :group_id
    end

    class Group < ApplicationRecord
        has_many :contact_groups
        has_many :contacts, through: :contact_groups
    end

From what I understand from reading the docs, this setup is correct. If I run `Contact.counter_culture_fix_counts`, everything works fine. If I try to create a new contact, like so, I get the following error.

    c = Contact.new(attrs)
    [9] pry(main)> #<Contact id: nil, first_name: "Billy", last_name: "The Kid", email: "bkid@example.com" ...>
    c.valid?
    [10] pry(main)> true
    c.save
    [11] pry(main)> c.save
    (0.2ms)  BEGIN
    Contact Exists (0.5ms)  SELECT  1 AS one FROM "contacts" WHERE "contacts"."email" = 'bkid@example.com' LIMIT 1
    Contact Exists (0.5ms)  SELECT  1 AS one FROM "contacts" WHERE "contacts"."email" = 'bkid@example.com' AND "contacts"."company_id" = 94 LIMIT 1
    Contact Exists (0.6ms)  SELECT  1 AS one FROM "contacts" WHERE "contacts"."preferences_token" = '6dc8b7943f87efd81477450c199e6ecf' LIMIT 1
    SQL (1.2ms)  INSERT INTO "contacts" ("first_name", "last_name", "email", "created_at", "updated_at", "company_id", "color", "encrypted_password", "confirmation_token", "confirmation_sent_at", "unconfirmed_email", "request_email_frequency", "invite_email_sent_at", "preferences_token", "key") VALUES ('Billy', 'The Kid', 'bkid@example.com', '2017-07-20 18:24:16.880278', '2017-07-20 18:24:16.880278', 94, '#344B59', '$2a$10$baAhoJtROfmJRx1ymb7aX.5s/5u.99..fT9OsC9MvoKEpmT4olq.G', '6dc8b7943f87efd81477450c199e6ecf', '2017-07-20 17:50:50.005270', 'bkid@example.com', 'Daily', '2017-07-20 17:50:50.033649', '6dc8b7943f87efd81477450c199e6ecf', 'Billy-dedf62') RETURNING "id"
    (0.3ms)  ROLLBACK
    ArgumentError: The method .group() must contain arguments.
    from /Users/ACIDSTEALTH/.gem/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation/query_methods.rb:1214:in `check_if_method_has_arguments!'

I've been struggling to figure out what's causing this for some time and so far my only working theory is that there is a name clash with my model `Group` and ActiveRecord's `.group()` method. I'm considering renaming `Group` to something else, but that's obviously a lot of work, so I'd like to first find out if my theory is correct, if possible. Thoughts?

**Comment by magnusvk** [comment]
@danielbonnell this is a fun one; counter_culture uses `send` to get to the other side of the relation, so in this case it calls `.group` on a `ContactGroup` which is what goes wrong here because that's an ActiveRecord method, not the association method.

That's technically a bug in counter_culture—it should probably handle reserved method names like this better.

That being said, I think you have the `counter_culture` calls in the wrong place. Creating a new `Contact` in and of itself doesn't cause the count to change, it's the creation of the `ContactGroup` that does. A good rule-of-thumb is that `counter_culture` should be called in the model that has the `belongs_to` relationship.

Furthermore, in the second call your `column_name` doesn't match what you have in `column_names`: You'd have to pass a `Proc` to `column_name` that returns `:confirmed_count` or `nil` depending on the value of `confirmed_at`.

And then if you fix all that, you'll probably find that `counter_culture_fix_counts` won't work correctly because you'd have to join to `contacts` from `contact_groups`. I'd recommend just writing your own method that fixes counts to work around that and using `skip_unsupported` for the normal counter cache.

**Comment by danielbonnell** [comment]
Thanks @magnusvk , I ended up just reverting all the new counters like the one above and using the background job that I had before to manually update the counts. Thought I could get this to work but it just turned into an endless rabbit hole.
