### ISSUE TITLE
Count is not updated when destroy record with "dependent: :destroy" on relations

### ISSUE THREAD

**Issue by passalini** [magnusvk/counter_culture#182]
This gem does not work with this simple model:
```
class Registration < ActiveRecord::Base
  counter_culture :school
  
  belongs_to :school 
  has_many :enrollments, dependent: :destroy
end
```
If I remove the `dependent: :destroy` of the relation, the `count` is updated. But with this option, the gem does not work!

![image](https://user-images.githubusercontent.com/475974/28539250-6742a41c-7087-11e7-8758-b8c55cfdcf9c.png)

**Comment by magnusvk** [comment]
@passalini that seems strange, given that the `dependent: :destroy` isn't even on the relation that counter_culture uses. Can you open a pull request with a simple failing test case for this? Your screenshot doesn't actually help much because I have no idea what methods / objects you're working with there. Thanks.

**Comment by magnusvk** [comment]
Closing this; feel free to reopen as a PR with a failing test case.
