### ISSUE TITLE
Conditional counter cache not work

### ISSUE THREAD

**Issue by timshingyu** [magnusvk/counter_culture#192]
```
class Product < ActiveRecord::Base
  enum status: [
    :standard,
    :special
  ]

  belongs_to :category
  counter_culture :category, column_name: proc {|model| model.special? ? 'special_count' : nil }
end

class Category < ActiveRecord::Base
  has_many :products
end
```
Tried to setup the models above. When changed product status to :special `product.special!`, The `special_count` from Category model haven't updated as expected. Any idea?

**Comment by magnusvk** [comment]
I'm sorry, but I can't provide support like this because I have no idea what `special!` does. Perhaps it changes the value without callbacks? In that case this would not be expected to work. In any case, there's tests making sure this works, so I'm quite certain the problem is in your code. Feel free to open a pull-request with a failing test if that's not the case.
