### ISSUE TITLE
Database ID is nil inside column_name proc?

### ISSUE THREAD

**Issue by joemsak** [magnusvk/counter_culture#219]
I have a counter culture in an AR model like so

It's a `Score` which belongs to a `Submission` and a `Judge` 

(all data is already persisted at runtime and in context of this error)

```ruby
class Score < ActiveRecord::Base
#...

  belongs_to :submission
  belongs_to :judge

#....

  counter_culture :submission,
    column_name: Proc.new { |model|

      binding.irb
      > model.id
      => nil
      > model.judge
      => nil

     # ...
    }, 
   # column_names: {...

#...
end
```

Not sure what's happening here but I'm actually trying to change the judge association to another record, and then save the score

When I debug before calling save on the score, I get a database ID and the correct (changed) judge record

```ruby
# Some task script that will eventually trigger the counter culture callback above...

score = Score.find(a)
judge = Judge.find(b)

# both exist

score.judge = judge

binding.irb
> score.id
=> a
> score.judge
=> judge
> score.judge_id
=> b

score.save
# counter_culture callbacks fail because judge is nil
```

When I debug inside the callback as shown above, both these things are nil, which is causing errors in the code that's trying to accomplish the task

**Comment by magnusvk** [comment]
I'm not sure what you're trying to do here exactly and I can't repro with the above.

FWIW you would expect the `id` to sometimes be `nil` because counter_cache has to figure out what the column name was before any changes in the update callback and does this by duping the model and reverting the changes ([see here](https://github.com/magnusvk/counter_culture/blob/3070845a4af6a3076c66f488f3af7d7feba0c762/lib/counter_culture/extensions.rb#L122)). I struggle to see why you would use the id to determine the column name, so that has never been supported.

However, you would definitely expect the judge to be correct. Was it perhaps `nil` before you assigned the judge? Then you'd your `Proc` to be called twice: once with `nil` and then with the real value.

Unfortunately I can't help here further without being able to reproduce this. If you still think this is a bug, could you isolate a test case and open a pull-request that includes the failing test?

Thank you.

**Comment by joemsak** [comment]
@magnusvk So yeah, I reported the ID nil because that really surprised me, and I found this when what I was really trying to check was the judge relationship. I didn't know I should expect a copy of the model with a nil ID so that's why I reported the nil ID and not the nil judge directly

So the issue was I was trying to assign a new judge, as the old record was accidentally deleted, and I was assigning a newly created record from a database backup

However, I believe the scores were only marked as deleted (by acts as paranoid) as they were dependent on the judge, I'm not sure that rails or any other lib would have removed the judge id, merely sent the destroy command (which is protected by acts as paranoid)

And this happens during save *after* I assigned the judge, as you can see in my second code example, so before save, the new judge profile should be there, as confirmed by a debugging session right before the save line

I will try to reproduce in an isolated environment and when I do I'm sure I'll find the mistake in my application code :D thanks

**Comment by magnusvk** [comment]
So you're doing an update here, not a create; therefore counter_culture needs to determine the column name twice: once in the state _before_ your changes and once _after_ your changes. Then it'll decrement the old column name and increment the new column name. This way the counts will change correctly if the calculated column name changes. If it doesn't change, it's a no-op.

But given all that you'd expect the `judge` to be `nil` on the first call—as that's what it was before your save. It doesn't matter that it's not `nil` before the save, as counter_culture reconstructs the model as it was when you loaded it form the database.

If you want this to work, you'll have to write code in your `Proc` that will work with the state of the instance both with and without your changes.

**Comment by joemsak** [comment]
@magnusvk Thank you, I appreciate your explanation! It wasn't clear to me that it has a before and after mechanism. Perhaps I missed it in my glance at the usage docs. Cheers

**Comment by magnusvk** [comment]
It's quite possible this isn't properly documented. 😄
