### ISSUE TITLE
Gem does not properly deduce namespaced classes database table name

### ISSUE THREAD

**Issue by rlugge** [magnusvk/counter_culture#232]
Overview:

I have two classes -- call them `FooBar::Show` and `FooBar::Act`.  Each show has many acts.  Show has a column `foo_bar_act_count` (defined with `null: false, default: 0`).  Add 'counter_culture :show` to the act class to tell Counter Culture to maintain my count column.

Expected Behaviour:

Running `FooBar::Act.counter_culture_fix_counts` should update the count values in the various Show records, with counter culture recognizing that the table name should be `foo_bar_act_count`.

Actual Behaviour:

Running `FooBar::Act_counter_culture_fix_counts` generates an error about `foo_bar_shows.foo_bar` does not exist.  Investigating the actual query, it is attempting to reference `"foo_bar_shows".foo_bar/acts_count`, a clearly invalid table name.

Workaround:

I can work around this easily by defining the counter column (`counter_culture :show, column_name: 'foo_bar_acts_count'`), but it seems odd that I should have to.  If the gem had generated a valid column name I'd consider shrugging it off, but the fact that the gem produces a column name that is, on it's face, invalid, suggests there is a genuine bug here.

**Comment by magnusvk** [comment]
@rlugge I think I have a fix in #234, but I still have to wait for the tests to go green in CI.

However, I would say the correct behavior here is actually to expect `acts_count` rather than `foo_bar_acts_count`, though arguably that's debatable. In any case, it should be better behavior than including a slash which is just always wrong.
