### ISSUE TITLE
Supported Ruby version is still >= 2.3, right?

### ISSUE THREAD

**Issue by deanmi** [magnusvk/counter_culture#285]
Hi,

First, I want to thank you for creating such an awesome gem! I'd like to make sure that I understand the change log comment for v2.5.0, which says dropped support for Ruby 2.3 and 2.4. The [gemspec still says 2.3 and greater](https://github.com/magnusvk/counter_culture/blob/78359792a287fbfe063609bfa2d558a289b37b8c/counter_culture.gemspec#L16), and looking at the commits for 2.5.0 it looks like you just dropped test support for 2.3 and 2.4.  Is that correct?  In other words, counter_culture should still work with Ruby 2.3 and above, correct?   Thanks!

**Comment by magnusvk** [comment]
@deanmi well—it *probably* works. Given that it's not tested anymore and that Ruby 2.3 is EOL there's no guarantees. And I do remember there being at least one test failure—otherwise I wouldn't have dropped testing for it. But it's quite possible it was something obscure like a gemset failure or a feature you don't use. So yeah, if it works for you, no reason to panic. At the same time, you should probably upgrade anyhow. ;)
