### ISSUE TITLE
destroy_all is causing negative counts

### ISSUE THREAD

**Issue by vanboom** [magnusvk/counter_culture#286]
```ruby
class User
  has_many :posts
end
class Post
  belongs_to :user, touch: true
  counter_culture :user, touch: true
end
```

I have tried removing the touch options.  It seems counter culture is double counting the destruction.  If the deleted count is `5`, the counter becomes `-5` after the `destroy_all`, e.g. user.posts.destroy_all

**Comment by magnusvk** [comment]
@vanboom I added a spec for this in https://github.com/magnusvk/counter_culture/commit/b171e6eeed80805996de9d4abc0687e00a78ea54 and it passes for me locally, so I have to assume this is something caused by your application code. If not, please open a pull request with a failing test case that isolates this behavior so I can reproduce.

**Comment by vanboom** [comment]
Ok, thank you.  I will investigate further.  I have confirmed that there are no Rails counter_cache features enabled on these models.
