### ISSUE TITLE
after_update callback

### ISSUE THREAD

**Issue by stahor** [magnusvk/counter_culture#329]
Hi there. I need some callback that is fired right after/around counter update. In my scenario, I already have a paper_trail integration that creates versions before counters are updated. So I need some way to fix data in those versions. 

It looks like adding this logic somewhere [here](https://github.com/magnusvk/counter_culture/blob/master/lib/counter_culture/counter.rb#L114) should do the trick.

Do you have any better ideas/objections?

**Comment by magnusvk** [comment]
Does the existing PaperTrail integration not solve this for you? https://github.com/magnusvk/counter_culture#papertrail-integration

**Comment by stahor** [comment]
Nope, I already have a code that creates versions and this integration will create duplicates.

**Comment by magnusvk** [comment]
Why rely on your custom code if there's already an integration that works and saves the correct data to PaperTrail? It doesn't seem worth it to me to add callbacks just for this.

**Comment by mattboldt** [comment]
Not sure if I'm going about this in the most idiomatic way, but I too am looking for a way to listen for updates to the counter cache.

My scenario is my parent object, let's call it a `Book` that `has_many :pages` with a `page_count` counter cache. If a `Page` is added, removed, or changed, and counter_culture does its thing, I need to spin up a background job to re-generate a PDF document with all the pages in the `Book`.

Right now I'm considering queuing this job manually, or in an `after_save` callback on the `Page` model. I'm also considering switching careers because I have to work with PDFs, callbacks, and background jobs at the same time.

**Comment by magnusvk** [comment]
Haha, yeah, I mean, architecturally I think what you _should_ do in this case is move any updates to anything in a `Book` to a service that updates the PDF after it persists any changes. But realistically the shortest path to getting your scenario to work would be an `after_save` on `Page`. That's what triggers counter_culture, too.
