### ISSUE TITLE
Touch: true isn't triggering after_touch callback

### ISSUE THREAD

**Issue by louiswdavis** [magnusvk/counter_culture#400]
We have the following setup to run a job via a callback when any save is made to a `Profile` and want to be able to include saves made to our `accepted_count` counter_culture field which are not picked up with the normal `after_save`.

We tried using `touch: true` and an `after_touch` callback but this doesn't run as expected.

```ruby
class Profile < ApplicationRecord
  has_many :profile_requests, dependent: :destroy

  after_save :run_job
  after_touch :run_job
end
```

```ruby
class ProfileRequest < ApplicationRecord
  belongs_to :profile

  enum status: { pending: 0, accepted: 1, declined: 2, expired: 3, withdrawn: 4 }

  counter_culture :profile,
    column_name: proc { |profile_request| profile_request.accepted? ? :accepted_count : nil },
    column_names: -> { { ProfileRequest.accepted => :accepted_count } },
    touch: true
```

We're looking into an alternative setup to run the callback but are curious why the touch: true doesn't trigger it, if this is a bug, and if there's a known way of triggering a callback after a `counter_culture` update.

The callback does trigger when we tried `Profile.first.touch` in the console

**Comment by magnusvk** [comment]
Unfortunately I don't have a good solution for you here. It's intentional that counter_culture doesn't trigger further callbacks. This runs the risk of a heavy chain of updates running when, really, we should just be updating the counter cache column. This should be as lightweight as possible an operation. The `touch: true` option just adds a way to bump the `updated_at` timestamp, it's not a "full touch" in the sense it doesn't call `model.touch`

You could probably add an `after_save` callback on `ProfileRequest` in your example, and then call `run_job` from there, but it's a bit janky as you're duplicating some of the logic in counter_culture to determine whether to update the counter or not.
