### ISSUE TITLE
OFFSET is slow on postgres, makes fixing counter values slow

### ISSUE THREAD

**Issue by jordan-thoms** [magnusvk/counter_culture#79]
Hi

According to the postgres documentation ( http://www.postgresql.org/docs/9.3/static/queries-limit.html ), "The rows skipped by an OFFSET clause still have to be computed inside the server; therefore a large OFFSET might be inefficient."

This is matching what I'm seeing - we have a table with ~1.2 million rows, and the start of the table is queried very quickly, and it gradually slows down until the final queries are taking well over a second each. 

Seems that for rows using numeric ids it'd be possible to use a BETWEEN on the id instead (with the caveat that deleted rows could cause less than 1000 rows to be selected). Not sure what to do for tables with uuid keys.

Cheers

**Comment by xtagon** [comment]
We're using UUIDs and just noticed this problem. Migration took way too long to run and we had to kill it. Anyone have an idea for a solution?

**Comment by magnusvk** [comment]
@xtagon see my last comment for an idea on how to fix this. Happy to look at a PR if you try this and it works.

**Comment by xtagon** [comment]
@magnusvk Thanks, it will take me some time to put together a test with a fork. I'll let you know what comes of it.

**Comment by magnusvk** [comment]
@xtagon @jordan-thoms Just thinking about this again: It turns out we use Rails' `find_in_batches` since gem version 0.2.0 which does _not_ use `OFFSET` and rather queries on the primary key instead. So if you update to a current gem version you shouldn't see this issue.

Of course, there might be other reasons for your migration taking too long, like missing indexes.

**Comment by xtagon** [comment]
I tried this with the latest version of the gem, and it actually does use offset to get the count per batch. And it's way too slow still, because for a large number of rows, the count query cost increases drastically with every batch.

**Comment by xtagon** [comment]
Hi, I must appologize. I incorrectly believed the OFFSET was being used - in reality, my app had a patch from 2015 before find_in_batches was fixed for UUIDs (see https://github.com/rails/rails/issues/5786)

However, even with removing that patch, the migration is extremely slow. I would be interested in a version that does a more efficient update_all but I don't know where to begin and I'm still largely unfamiliar with this code base.

Does anyone have any new ideas?

**Comment by magnusvk** [comment]
Really hard to tell without knowing more about your schema. You'll probably want to look at the queries it runs and use `EXPLAIN` to figure out why they're slow.

**Comment by xtagon** [comment]
I'm happy to provide more information if it helps. I'll gather some details and post it back soon.

**Comment by xtagon** [comment]
I have the following schema:

- Subject has many SubjectPhotoAssignments
- Subject table has `photos_count` column
- SubjectPhotoAssignment belongs to Subject
- SubjectPhotoAssignment has `counter_culture :subject, column_name: "photos_count"`

The counter cache here was not added until late in the product's life, so right now we have around 1599435 `subjects` rows and 1671735 `subject_photo_assignments` rows.

Some subjects already have the correct count, but for the most part nearly all of them need to be fixed.

When I run `SubjectPhotoAssignment.counter_culture_fix_counts, only: :subject` it starts to do the job, and runs continuously and when I run it on a copy of the production dataset, it takes so long I haven't been able to finish it yet. Perhaps it would finish in a few hours, but I keep having to stop it to do other things. In any case, a few hours isn't an acceptable time for this migration since it ties up the DB with constant activity and would slow down our production system considerably.

Some observations:

Here is an example of what the batches look like in the logs:

```
  Subject Load (797.5ms)  SELECT  "subjects".id, "subjects".id, COUNT("subject_photo_assignments".id)*1 AS count, "subjects".photos_count FROM "subjects" LEFT JOIN "subject_photo_assignments" AS subject_photo_assignments ON "subjects".id = subject_photo_assignments.subject_id WHERE ("subjects"."id" > '5ec92f72-ee06-42dd-a1e5-b42cd479dda9') GROUP BY "subjects"."id"  ORDER BY "subjects"."id" ASC LIMIT 1000
   (0.3ms)  BEGIN
   (0.3ms)  SELECT COUNT(*) FROM "subject_photo_assignments" WHERE "subject_photo_assignments"."subject_id" = $1  [["subject_id", "5ec93a60-8010-4ffe-9954-aad7b4f1f6f3"]]
  SQL (0.3ms)  UPDATE "subjects" SET "photos_count" = 1 WHERE "subjects"."id" = $1  [["id", "5ec93a60-8010-4ffe-9954-aad7b4f1f6f3"]]
   (0.2ms)  SELECT COUNT(*) FROM "subject_photo_assignments" WHERE "subject_photo_assignments"."subject_id" = $1  [["subject_id", "5ec9421b-fe02-41da-9735-2d98f9e334c0"]]
  SQL (0.2ms)  UPDATE "subjects" SET "photos_count" = 1 WHERE "subjects"."id" = $1  [["id", "5ec9421b-fe02-41da-9735-2d98f9e334c0"]]
   (0.2ms)  SELECT COUNT(*) FROM "subject_photo_assignments" WHERE "subject_photo_assignments"."subject_id" = $1  [["subject_id", "5ec96261-d30f-4470-b5e2-af128f65cd90"]]
  SQL (0.3ms)  UPDATE "subjects" SET "photos_count" = 1 WHERE "subjects"."id" = $1  [["id", "5ec96261-d30f-4470-b5e2-af128f65cd90"]]
   (0.2ms)  SELECT COUNT(*) FROM "subject_photo_assignments" WHERE "subject_photo_assignments"."subject_id" = $1  [["subject_id", "5ec98161-58e5-4286-8d29-7be9bec0a7a4"]]
  SQL (0.2ms)  UPDATE "subjects" SET "photos_count" = 1 WHERE "subjects"."id" = $1  [["id", "5ec98161-58e5-4286-8d29-7be9bec0a7a4"]]
   (0.3ms)  SELECT COUNT(*) FROM "subject_photo_assignments" WHERE "subject_photo_assignments"."subject_id" = $1  [["subject_id", "5ec9824b-c388-4fea-b1b6-804767b514e9"]]
  SQL (0.3ms)  UPDATE "subjects" SET "photos_count" = 1 WHERE "subjects"."id" = $1  [["id", "5ec9824b-c388-4fea-b1b6-804767b514e9"]]
```

I've elided it since it repeats those SELECT COUNT and UPDATE queries for all subjects in the batch. Then this pattern repeats for each batch of 1000 subjects.

Here is an EXPLAIN ANALYZE of that first query, the Subject Load query that happens once at the start of each batch: 

```
                                                                                                        QUERY PLAN                                                                                                         
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.85..830.53 rows=1000 width=44) (actual time=847.713..856.331 rows=1000 loops=1)
   ->  GroupAggregate  (cost=0.85..1058814.36 rows=1276175 width=44) (actual time=847.712..856.207 rows=1000 loops=1)
         Group Key: subjects.id
         ->  Merge Left Join  (cost=0.85..1036481.30 rows=1276175 width=36) (actual time=847.667..855.491 rows=1077 loops=1)
               Merge Cond: (subjects.id = subject_photo_assignments.subject_id)
               ->  Index Scan using subjects_pkey on subjects  (cost=0.43..877028.80 rows=1276175 width=20) (actual time=0.042..5.735 rows=1001 loops=1)
                     Index Cond: (id > '5ec92f72-ee06-42dd-a1e5-b42cd479dda9'::uuid)
               ->  Index Scan using index_subject_photo_assignments_on_subject_id_and_photo_id on subject_photo_assignments  (cost=0.43..141633.61 rows=1671823 width=32) (actual time=0.003..763.676 rows=619969 loops=1)
 Planning time: 4.229 ms
 Execution time: 856.817 ms
(10 rows)
```

I also observed that a significant number of `photo_count`s are supposed to be 1 (after it is fixed). It is a little less common to have a count other than 0 or 1. That means that at least for my specific use case, there should be a way to make those repeated individual UPDATE commands coalesced into an UPDATE_ALL. Do you think that would  be worth persuing?

I believe it is also possible to do more advanced SQL in an UPDATE ALL in the case of Postgres. For example, here is a snippet of code we wrote to update a one to one "default" association in a one to many relationship, which if you think about it, is not that different from a counter cache:

```
UPDATE subjects
SET primary_subject_photo_assignment_id = (
  SELECT subject_photo_assignments.id
  FROM subject_photo_assignments
  WHERE subject_id = subjects.id
  ORDER BY "position" ASC
  LIMIT 1
)
WHERE primary_subject_photo_assignment_id IS NULL
```

Is there any other information that would be useful?

BTW Thanks again for helping me. I appreciate it greatly.

**Comment by magnusvk** [comment]
Something weird is going on there for you. It shouldn't issue a separate count query for every object, the single slow query at the beginning is the only thing that counter_culture issues. You can see this in the code, and I also verified that by running the tests and looking at the SQL queries. It should be only the slow, big query for the whole batch at the beginning, and then updates only for incorrect counts.

Are you using the latest version? Are you using a modified version of counter_culture? Are you patching ActiveRecord? I have no idea where those individual COUNT queries come from.

Also, the updates are fairly quick. I don't think you'd get much improvement from batching them and it'd be complicated to implement.

My gut also tells me that the big count query shouldn't be this slow. Less than two million rows is not that much as far as databases go, why is that so slow? What kind of a database are you using?

Anyhow, I probably won't be able to help much more with this, as this doesn't look to be a direct counter_culture issue.

**Comment by xtagon** [comment]
I am using the latest version, and not a modified version of counter_culture, and not patching ActiveRecord. I did have a monkey patch for find_in_batches before, but I removed that and tested again before pasting those results for you. That solved what I was seeing with OFFSET before.

Based on what you are saying I think something funky is going on with my setup  but I'm not quite sure what it is. I just forked and ran the tests for your repo and I am seeing the same thing you are seeing where it isn't making those extra count queries.

I will keep looking into this on my side. Thank you for your support so far.

**Comment by xtagon** [comment]
Turns out this is simple enough that counter_culture can be sidestepped. I'm leaving this here in case anyone in the future finds this issue and needs to update millions of records in under a minute:

```
      connection.execute <<~SQL
        UPDATE subjects SET photos_count = (
          SELECT COUNT(*) FROM subject_photo_assignments
          WHERE subject_photo_assignments.subject_id = subjects.id
        )
      SQL
```

It does recompute the entirety of the subjects even if only some have changed, but it was fast.

Thanks again @magnusvk for being patient with me.

**Comment by Freddy03h** [comment]
@xtagon thank you from the future 👍
